<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \Magento\Catalog\Block\Product\Image */ ?>

<span class="product-image-container Bynder-CDN"
      style="width:<?= $escaper->escapeHtmlAttr($block->getWidth()) ?>px;">
    <span class="product-image-wrapper"
          style="padding-bottom: <?= ($block->getRatio() * 100) ?>%;">
        <img class="<?= $escaper->escapeHtmlAttr($block->getClass()) ?>"
        <?= $escaper->escapeHtmlAttr($block->getCustomAttributes()) ?>
             src="<?= $escaper->escapeUrl($block->getImageUrl()) ?>"
             max-width="<?= $escaper->escapeHtmlAttr($block->getWidth()) ?>"
             max-height="<?= $escaper->escapeHtmlAttr($block->getHeight()) ?>"
             alt="<?= /* @noEscape */ $block->stripTags($block->getLabel(), null, true) ?>"/></span>
</span>
