<?php
$product = $block->getProduct();

$document_text = $product->getData('bynder_document');

$document_array = json_decode($document_text, true);
//echo "<pre>"; print_r($document_array); die;
$html = "";
if (!empty($document_array)) {
    foreach ($document_array as $doc) {
        $lable = explode("/", $doc['item_url']);
        $html .= '<li><a href="' . $doc['item_url'] . '">' . $lable[6] . '</a></li>';
        
    }
}
?>

<ul>
    <?= /* @noEscape */ $html ?>
</ul>
