
<input type="hidden"
    name="<?= $escaper->escapeHtml($block->getNPrefix()) ?>"
    value="" /><!-- this is send if nothing is checked -->
<ul class="checkboxes">
    <?php foreach ($block->getValues() as $name => $label): ?>
        <li>
            <input type="checkbox" value="<?= $escaper->escapeHtml($name) ?>"
                name="<?= $escaper->escapeHtml($block->getNPrefix()) ?>[]"
                id="<?= $escaper->escapeHtml($block->getId() . '_' . $name) ?>"
                <?= ($escaper->escapeHtml($block->getCheck($name)) ? ' checked="checked"' : '') ?> />
            <label for="<?=$escaper->escapeHtml($block->getId() . '_' . $name) ?>">
                <?=  $escaper->escapeHtml($label) ?>
            </label>
        </li>
    <?php endforeach; ?>
</ul>
