<div class="pp-buttons-container">
    <?php echo $block->getButtonHtml(); ?>
</div>
<script>
    require([
        'jquery',
        'prototype'
    ], function($) {

        $('#bt_id_2').click(function() {
            var product_sku = $('textarea#byndersyncdata_bynder_sync_data_sku').val();
            var select_attribute = $('select#byndersyncdata_bynder_sync_data_select').val();
            console.log(select_attribute);
            var params = {
                product_sku: product_sku,
                select_attribute: select_attribute
            };
            new Ajax.Request('<?php echo $block->getAjaxUrl() ?>', {
                parameters: params,
                loaderArea: true,
                asynchronous: true,
                /*onCreate: function() {
                    $('#byndersyncdata_bynder_sync_data_sku').text('');
                },*/
                beforeSend: function() {
                    $('body').trigger('processStart');
                },
                onSuccess: function(transport) {
                    var response = JSON.parse(transport.responseText);
                    
                    var resultText = '';
                    if (response.status == 1) {
                        resultText = response.message
                        console.log(response.message);
                        $('#byndersyncdata_bynder_sync_data_sku').text(resultText);
                        $(".success-msg-sync").show();
                        $(".error-msg-sync").hide();
                        $(".success-msg-sync").html("Sku Get Successfully...!");
                        setTimeout(function() { // wait for 5 secs(2)
                            //location.reload(); // then reload the page.(3)
                            $('.success-msg-sync').delay(5000).fadeOut('slow');
                        }, 5000);
                    } else {
                        resultText = transport.statusText;
                        $('#byndersyncdata_bynder_sync_data_sku').text('');
                        $(".success-msg-sync").hide();
                        $(".error-msg-sync").show();
                        $(".error-msg-sync").html("There is not any empty Bynder Data in product.");
                        setTimeout(function() { // wait for 5 secs(2)
                            //location.reload(); // then reload the page.(3)
                            $('.error-msg-sync').delay(5000).fadeOut('slow');
                        }, 5000);
                    }

                }
            });
        });
    });
</script>